<?php

require_once dirname(__FILE__).'/../../../../TestHelper.php';
require_once 'Diggin/Scraper/Helper/Simplexml/Pagerize.php';

/**
 * Test class for Diggin_Scraper_Helper_Simplexml_Autodiscovery.
 * Generated by PHPUnit on 2009-04-29 at 01:05:51.
 */
class Diggin_Scraper_Helper_Simplexml_Pagerize_HAtomTest extends PHPUnit_Framework_TestCase
{
    protected $object;
    
    protected function setUp()
    {
        $this->object = new Diggin_Scraper_Helper_Simplexml_Pagerize($this->getSimpleXml());
    }
    
    public function testA()
    {
        
    }
    
    public function testHAtomNextLink()
    {
        var_dump($this->object->hAtomNextLink());
    }
    
    private function getSimpleXml()
    {
        $html = file_get_contents(dirname(__FILE__).'/_files/newsaolom.html');
        $dom = new DOMDocument();
        @$dom->loadHTML($html);
        
        return @simplexml_import_dom($dom);
    }
}