<?php
require_once 'PHPUnit/Framework.php';

require_once 'Diggin/Scraper.php';
require_once 'Zend/Http/Client.php';
require_once 'Zend/Http/Client/Adapter/Test.php';

/**
 * Test class for Diggin_Scraper.
 * Generated by PHPUnit on 2009-01-16 at 22:23:44.
 */
class Diggin_Scraper_Relase06Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Scraper
     * @access protected
     */
    protected $object;

    private $_responseHeader200 = "HTTP/1.1 200 OK\r\nContent-type: text/html";
    
    
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        //var_dump(get_include_path());
        require_once 'Diggin/Http/Response/Encoding.php';
        Diggin_Http_Response_Encoding::setDetectOrder('ascii, sjis-win, shift-jis');
        $this->object = new Diggin_Scraper;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    public function testCharactorSet()
    {

$header = "HTTP/1.1 200 OK" ."\r\n".
           "Content-type: text/html; charset=Shift-JIS;"; // ... or SJIS-win ?
$html = <<<HTML
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html lang="ja" xml:lang="ja" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta content="text/html; charset=Shift-JIS" http-equiv="Content-Type" />
</head>
<body>
① ㈱① ㈱① ㈱① ㈱① ㈱～① ㈱① ㈱① ㈱① ㈱
</body>
HTML;

// 28.05 2010 added
$html = mb_convert_encoding($html, 'SJIS-win', 'UTF-8');
$response = Zend_Http_Response::fromString("$header\r\n\r\n$html");

$scraper = new Diggin_Scraper;
$ret = $scraper->process('//body', 'test => text')->scrape($response);

    $this->assertEquals($ret['test'], '① ㈱① ㈱① ㈱① ㈱① ㈱～① ㈱① ㈱① ㈱① ㈱');

    }

    //
    //Don't use this test 
    public function _testUseHttp()
    {
        $targetUrl =
            'http://www.microsoft.com/japan/office/previous/2003/experience/workstyle/tips/word/tips9.mspx';


        $scraper = new Diggin_Scraper();
        $results = $scraper->
                process('h2.subtitle', 'test => "TEXT"')->
                    scrape($targetUrl);

        var_dump($results);
    }

}
?>
