<?php
require_once 'PHPUnit/Framework.php';

require_once 'Diggin/Scraper/Helper/Simplexml/Title.php';

/**
 * Test class for Diggin_Scraper_Helper_Simplexml_Title.
 * Generated by PHPUnit on 2009-03-27 at 23:11:39.
 */
class Diggin_Scraper_Helper_Simplexml_TitleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Scraper_Helper_Simplexml_Title
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        
        $responseBodyWithHeadTag1 = '<html lang="ja">'.PHP_EOL.
                           '<head>'.PHP_EOL.
                           "<title>first</title>".
                           '<title>second</title>'.
                           '</head>'.
                           '<body>'.PHP_EOL.
                           '<a href="test/test.html">testlink</a><br /><br />'.PHP_EOL.
                           '</body>'.PHP_EOL.
                           '</html>';
        $simplexml = simplexml_load_string($responseBodyWithHeadTag1);
        $this->object = new Diggin_Scraper_Helper_Simplexml_Title($simplexml);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testDirect().
     */
    public function testDirect() {
        $expect = 'first';

        $this->assertEquals($expect,
                            $this->object->direct());
 
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
