<?php
require_once 'PHPUnit/Framework.php';

require_once 'Diggin/Uri/Http.php';

/**
 * Test class for Diggin_Uri_Http.
 * Generated by PHPUnit on 2008-09-30 at 22:45:31.
 */
class Diggin_Uri_HttpTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Uri_Http
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Diggin_Uri_Http;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @dataProvider checkUrlProvider
     */
    public function testGetAbsoluteUrl($base, $path, $expected)
    {
        $this->object->setBaseUri($base);
        $this->assertEquals($expected, $this->object->getAbsoluteUrl($path));

        
        ////htmlspecialcharsの場合
        //@see http://nkst.jp/vote2/novel.php?auther=20080001&page=2
        //<center><a href="/vote2/novel.php?auther=20080001&amp;page=2" accesskey="#" title="next">[次ﾍﾟｰｼﾞ(#)]</a><br></center>
        //<a href="/vote2/novel.php?auther=20080001&amp;page=429" accesskey="" title="last">[最後へ]</a><br>
    }

    public function checkUrlProvider()
    {
        //base, path, expected 
        return array(
        array('http://www.rhaco.org/', 'http://yahoo.com/test/', 'http://yahoo.com/test/'),
    	// import from rhaco's doc-test
     	// @see http://rhaco.googlecode.com/svn/rhaco_1_x/trunk/network/Url.php
        array('http://www.rhaco.org/', '/doc/ja/index.html', 'http://www.rhaco.org/doc/ja/index.html'),
        array('http://www.rhaco.org/', '../doc/ja/index.html', 'http://www.rhaco.org/doc/ja/index.html'),
        array('http://www.rhaco.org/', './doc/ja/index.html', 'http://www.rhaco.org/doc/ja/index.html'),
        array('http://www.rhaco.org/doc/ja/', './index.html', 'http://www.rhaco.org/doc/ja/index.html'),
        array('http://www.rhaco.org/doc/ja/', '../index.html', 'http://www.rhaco.org/doc/index.html'),
        array('http://www.rhaco.org/doc/ja/', '../../index.html', 'http://www.rhaco.org/index.html'),
        array('http://www.rhaco.org/doc/ja/', '../././.././index.html', 'http://www.rhaco.org/index.html'),
        array('http://www.rhaco.org/doc/ja', '/index.html', 'http://www.rhaco.org/index.html'),
        array('http://www.rhaco.org/doc/ja/action.html', 'index.html', 'http://www.rhaco.org/doc/ja/index.html'),
        //@see http://d.hatena.ne.jp/kitamomonga/20080410/ruby_mechanize_percent_url_bug
        array('http://www.rhaco.org/doc/ja/sample.cgi?query=key', '?param=test', 'http://www.rhaco.org/doc/ja/sample.cgi?param=test'),
        array('http://test.org/index.php', '?param=hoge', 'http://test.org/index.php?param=hoge'),
        // handleing space 
        //array('http://www.rhaco.org/doc/ja/', 'test space.html', 'http://www.rhaco.org/doc/ja/'.rawurlencode('test space.html'))
               
        );
    }

}
?>
