<?php
require_once 'PHPUnit/Framework.php';

require_once 'Zend/Http/Response.php';
require_once 'Diggin/Scraper/Strategy/Flexible.php';
require_once 'Diggin/Scraper/Process.php';

/**
 * Test class for Diggin_Scraper_Strategy_Flexible.
 * Generated by PHPUnit on 2009-01-18 at 06:23:01.
 */
class Diggin_Scraper_Strategy_FlexibleTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Scraper_Strategy_Flexible
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $responseHeader200 = "HTTP/1.1 200 OK\r\nContent-type: text/html";
        $responseBody = <<<BODY
<html><body>123aaaあ</body></html>
BODY;
        $response = Zend_Http_Response::fromstring("$responseHeader200\r\n\r\n$responseBody");
        $this->object = new Diggin_Scraper_Strategy_Flexible($response);
        //$this->object->getEvaluator()->setConfig(array('baseUrl' => 'http://base.example.net/test/'));
        $this->object->setBaseUri('http://base.example.net/test/');
        $this->object->getAdapter()->setConfig(array('url' => 'http://base.example.net/test/'));
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     */
    public function testSetAdapter() {

        $strategy = $this->object;
        
        require_once 'Diggin/Scraper/Adapter/Loadhtml.php';
        $loadhtml = new Diggin_Scraper_Adapter_Loadhtml();
        $strategy->setAdapter($loadhtml);

        $this->assertTrue($strategy->getAdapter() instanceof Diggin_Scraper_Adapter_Loadhtml);

        try {
            require_once 'Diggin/Scraper/Adapter/Normal.php';

            $strategy->setAdapter(new Diggin_Scraper_Adapter_Normal);
            $this->fail("Should not be able setStdClass");
        } catch (Diggin_Scraper_Strategy_Exception $e) {
        }

    }


    /**
     * @todo Implement testExtract().
     */
    public function testExtract() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

}
?>
