<?php
require_once 'PHPUnit/Framework.php';

require_once 'Diggin/Uri/Http.php';

/**
 * Test class for Diggin_Uri_Http.
 * Generated by PHPUnit on 2008-09-30 at 22:45:31.
 */
class Diggin_Uri_HttpTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    Diggin_Uri_Http
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new Diggin_Uri_Http;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * check getting absoluteUrl
     *
     *
     * import from rhaco's doc-test
     * @see http://rhaco.googlecode.com/svn/trunk/1_6_1/network/Url.php
     */
    public function testGetAbsoluteUrl()
    {
        $this->assertEquals('http://www.rhaco.org/doc/ja/index.html', 
                             $this->object->getAbsoluteUrl('/doc/ja/index.html', 'http://www.rhaco.org/'));
        $this->assertEquals('http://www.rhaco.org/doc/ja/index.html', 
                             $this->object->getAbsoluteUrl('../doc/ja/index.html', 'http://www.rhaco.org/'));
        $this->assertEquals('http://www.rhaco.org/doc/ja/index.html', 
                             $this->object->getAbsoluteUrl('./doc/ja/index.html', 'http://www.rhaco.org/'));
        $this->assertEquals('http://www.rhaco.org/doc/ja/index.html', 
                                                $this->object->getAbsoluteUrl('./index.html', 'http://www.rhaco.org/doc/ja/'));
        $this->assertEquals('http://www.rhaco.org/doc/index.html', 
                                                $this->object->getAbsoluteUrl('../index.html', 'http://www.rhaco.org/doc/ja/'));
        $this->assertEquals('http://www.rhaco.org/index.html', 
                                                $this->object->getAbsoluteUrl('../../index.html', 'http://www.rhaco.org/doc/ja/'));
        $this->assertEquals('http://www.rhaco.org/index.html', 
                                                $this->object->getAbsoluteUrl('../././.././index.html', 'http://www.rhaco.org/doc/ja/'));
        //$this->assertEquals('/www.rhaco.org/doc/index.html', 
        //                                        $this->object->getAbsoluteUrl('../index.html', '/www.rhaco.org/doc/ja/'));
        //$this->assertEquals('/www.rhaco.org/index.html', 
        //                     $this->object->getAbsoluteUrl('../../index.html','/www.rhaco.org/doc/ja/'));
        //$this->assertEquals('/www.rhaco.org/index.html', 
        //                                       $this->object->getAbsoluteUrl('../././.././index.html', '/www.rhaco.org/doc/ja/'));
        //$this->assertEquals('c:/www.rhaco.org/doc/index.html', 
        //                                        $this->object->getAbsoluteUrl('../index.html', 'c:/www.rhaco.org/doc/ja/'));
        $this->assertEquals('http://www.rhaco.org/index.html', 
                                                $this->object->getAbsoluteUrl('/index.html', 'http://www.rhaco.org/doc/ja'));
    }
}
?>
